# Generated by Django 2.1.7 on 2021-04-15 15:11

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=main.models.Todo.ten_minutes_hence),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('inprogress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
